[package]
name = "pylars"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
rand_distr = "0.4"
rayon = "1.10.0"
rand_xoshiro = "0.6.0"
pyo3 = { version = "0.23.4", features = ["extension-module"] }

[lib]
name = "pylars"
crate-type = ["cdylib"]
